# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('day_time', models.CharField(max_length=50)),
                ('true_label', models.CharField(max_length=50)),
                ('velocity', models.FloatField(default=0.0)),
                ('acceleration', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('specification_label', models.CharField(default='', max_length=50)),
                ('tp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_id', models.IntegerField()),
                ('end_point_id', models.IntegerField()),
                ('true_label', models.CharField(max_length=50)),
                ('infer_label', models.CharField(max_length=50)),
            ],
        ),
    ]
